#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Issue #18: the one real-AWS provisioning step, made safe and scripted.
# Creates the $1 zero-spend budget alarm, then a targeted Terraform apply of
# exactly the episode queue + DLQ (SQS-managed encryption, permanent free
# tier — $0/month). Everything else in terraform/ stays validated-never-
# applied; tests/test_sqs_wizard.py pins the target set below to enforce it.

TOTAL_STAGES=8

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TF_DIR="$REPO_ROOT/terraform"
TFVARS="$TF_DIR/terraform.tfvars"

BUDGET_TARGET="aws_budgets_budget.zero_spend"
SQS_TARGETS=(
  "aws_sqs_queue.dead_letter"
  "aws_sqs_queue.episodes"
  "aws_sqs_queue_redrive_allow_policy.dead_letter"
)
SQS_TARGET_FLAGS=("${SQS_TARGETS[@]/#/-target=}")

tf() { terraform -chdir="$TF_DIR" "$@"; }

fail() {
  printf '\n  %s✗ %s%s\n\n' "$RED" "$1" "$RESET"
  exit 1
}

# read_tfvar/write_tfvar deliberately mirror the library's _existing/write_env:
# this wizard's persisted values live in terraform/terraform.tfvars (HCL
# quoting), not in an .env file.

# read_tfvar KEY — current value of KEY in terraform.tfvars, unquoted.
read_tfvar() {
  [[ -f "$TFVARS" ]] || return 1
  local line
  line=$(grep -E "^${1}[[:space:]]*=" "$TFVARS" | tail -n1) || return 1
  line="${line#*=}"
  line="${line%%#*}"
  line="${line//\"/}"
  printf '%s' "$line" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'
}

# write_tfvar KEY VALUE — upsert `KEY = "VALUE"` into terraform.tfvars.
write_tfvar() {
  local key="$1" value="$2" tmp
  touch "$TFVARS"
  tmp=$(mktemp)
  grep -vE "^${key}[[:space:]]*=" "$TFVARS" > "$tmp" || true
  printf '%s = "%s"\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$TFVARS"
  printf '  %s✓ wrote%s %s → terraform/terraform.tfvars (gitignored)\n' \
    "$GREEN" "$RESET" "$key"
}

# assert_plan_creates_only PLANFILE ADDR... — refuse a saved plan that would
# create any resource outside this wizard's permitted footprint.
assert_plan_creates_only() {
  local planfile="$1" plan_json
  shift
  plan_json=$(mktemp)
  tf show -json "$planfile" > "$plan_json"
  if ! python3 - "$plan_json" "$@" <<'PY'
import json, sys

plan = json.load(open(sys.argv[1]))
allowed = set(sys.argv[2:])
creates = sorted(
    change["address"]
    for change in plan.get("resource_changes", [])
    if "create" in change.get("change", {}).get("actions", [])
)
unexpected = [address for address in creates if address not in allowed]
if unexpected:
    sys.exit(f"plan would create resources outside the wizard's scope: {unexpected}")
print(f"  plan creates only: {creates or 'nothing (already in place)'}")
PY
  then
    rm -f "$plan_json"
    fail "the saved plan reaches outside this wizard's permitted footprint — nothing was applied"
  fi
  rm -f "$plan_json"
}

budget_exists() {
  aws budgets describe-budget --account-id "$ACCOUNT_ID" \
    --budget-name "$BUDGET_NAME" \
    --query 'Budget.BudgetLimit.Amount' --output text >/dev/null 2>&1
}

banner "PathFinder — budget alarm + SQS targeted apply (issue #18)"

# ── Stage 1: preflight ────────────────────────────────────────────────────
stage "Preflight"
say "This wizard performs the project's one real-AWS provisioning step:"
step "creates the \$1/month zero-spend budget alarm (free — it has no actions)"
step "targeted-applies exactly the episode queue + its dead-letter queue"
step "prints the queue URLs the real-run runbook (docs/SETUP_WINDOWS.md §9.1) needs"
say ""
say "It will NOT touch EKS, Kinesis, S3, ECR, KMS, or IAM — those stay"
say "validated-never-applied. Standing cost of what it creates: \$0/month"
say "(SQS permanent free tier: 1M requests/month; this project uses hundreds)."
say ""
for tool in aws terraform python3; do
  command -v "$tool" >/dev/null 2>&1 || fail "$tool is not installed (brew install $tool)"
done
say "Found aws, terraform, and python3."
pause

# ── Stage 2: AWS credentials ──────────────────────────────────────────────
stage "AWS credentials"
if ! aws sts get-caller-identity >/dev/null 2>&1; then
  say "No working AWS credentials found — let's configure them."
  step "In the AWS console: IAM → your user → Security credentials → Create access key."
  open_url "https://console.aws.amazon.com/iam/home#/security_credentials"
  step "Copy the Access key ID and Secret access key, then enter them below"
  step "(region: us-east-1, output format: json)."
  say ""
  aws configure
  aws sts get-caller-identity >/dev/null 2>&1 || fail "credentials still don't work — re-run this wizard after aws configure succeeds"
fi
ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
CALLER_ARN=$(aws sts get-caller-identity --query Arn --output text)
say "Authenticated as: $CALLER_ARN"
say "Account:          $ACCOUNT_ID"
case "$CALLER_ARN" in
  *:root) warn "these are root-account credentials — an IAM user is safer, but this will work" ;;
esac
confirm "Provision into this account?" || fail "aborted — run aws configure for the intended account and re-run"

# ── Stage 3: terraform.tfvars ─────────────────────────────────────────────
stage "Terraform variables"
if [[ ! -f "$TFVARS" ]]; then
  cp "$TF_DIR/terraform.tfvars.example" "$TFVARS"
  say "Created terraform/terraform.tfvars from the example (gitignored)."
fi
GITHUB_REPOSITORY=$(read_tfvar github_repository || true)
if [[ -z "$GITHUB_REPOSITORY" ]]; then
  ask GITHUB_REPOSITORY "GitHub repo (owner/repo) [Dayallenr/Autonomous-Driving]:"
  [[ -z "$GITHUB_REPOSITORY" ]] && GITHUB_REPOSITORY="Dayallenr/Autonomous-Driving"
  write_tfvar github_repository "$GITHUB_REPOSITORY"
fi
CURRENT_EMAIL=$(read_tfvar budget_notification_email || true)
[[ "$CURRENT_EMAIL" == "you@example.com" ]] && CURRENT_EMAIL=""
say "The budget alarm emails you if the account ever accrues real spend."
if [[ -n "$CURRENT_EMAIL" ]]; then
  say "Current alarm email: $CURRENT_EMAIL"
  ask BUDGET_EMAIL "Alarm email [Enter keeps current]:"
  [[ -z "$BUDGET_EMAIL" ]] && BUDGET_EMAIL="$CURRENT_EMAIL"
else
  ask BUDGET_EMAIL "Email address for the budget alarm:"
fi
[[ "$BUDGET_EMAIL" == *@* ]] || fail "'$BUDGET_EMAIL' doesn't look like an email address"
write_tfvar budget_notification_email "$BUDGET_EMAIL"
REGION=$(read_tfvar aws_region || true)
[[ -z "$REGION" ]] && REGION="us-east-1"
CLUSTER_NAME=$(read_tfvar cluster_name || true)
[[ -z "$CLUSTER_NAME" ]] && CLUSTER_NAME="pathfinder"
BUDGET_NAME="${CLUSTER_NAME}-zero-spend"
QUEUE_NAME="${CLUSTER_NAME}-episodes"
say "Region: $REGION · queues: $QUEUE_NAME + ${QUEUE_NAME}-dlq · alarm: $BUDGET_NAME"
pause

# ── Stage 4: terraform init ───────────────────────────────────────────────
stage "Terraform init (local state)"
say "State stays in terraform/terraform.tfstate on this machine, gitignored —"
say "see the note in terraform/versions.tf for why there's no remote backend."
tf init -input=false >/dev/null || fail "terraform init failed — run 'terraform -chdir=terraform init' to see why"
say "Initialized."
pause

# ── Stage 5: the budget alarm — before anything else ──────────────────────
stage "Budget alarm (must exist before any apply)"
say "Planning the alarm (and only the alarm):"
# Always plan, even when the alarm already exists: a changed alarm email is
# an in-place update this plan picks up — skipping on existence would leave
# the new email unapplied and stage 7's clean-plan check failing.
budget_rc=0
tf plan -input=false -detailed-exitcode "-target=$BUDGET_TARGET" -out=wizard-budget.tfplan >/dev/null \
  || budget_rc=$?
case $budget_rc in
  0)
    say "Budget alarm already matches the configuration — nothing to change."
    ;;
  2)
    assert_plan_creates_only "$TF_DIR/wizard-budget.tfplan" "$BUDGET_TARGET"
    confirm "Create/update the \$1/month budget alarm emailing $BUDGET_EMAIL?" \
      || fail "aborted — nothing was applied"
    tf apply wizard-budget.tfplan || fail "terraform apply of the budget alarm failed"
    ;;
  *)
    fail "terraform plan for the budget alarm errored — run 'terraform -chdir=terraform plan -target=$BUDGET_TARGET' to see why"
    ;;
esac
say "Verifying against the AWS Budgets API..."
tries=0
until budget_exists; do
  tries=$((tries + 1))
  [[ $tries -ge 5 ]] && fail "budget alarm not visible in the Budgets API — refusing to continue to the queue apply without it"
  sleep 3
done
say "Budget alarm confirmed: $BUDGET_NAME (\$1/month, alerts at 1 actual cent)."
pause

# ── Stage 6: targeted apply of the queue pair ─────────────────────────────
stage "SQS queues — targeted apply"
budget_exists || fail "budget alarm missing — refusing to apply the queues without it"
say "Planning exactly the episode queue, its DLQ, and the DLQ's redrive-allow"
say "policy (an SQS attribute attachment, not a new billable resource) —"
say "the same shape the #22 rehearsal proved on LocalStack:"
tf plan -input=false "${SQS_TARGET_FLAGS[@]}" -out=wizard-sqs.tfplan >/dev/null \
  || fail "terraform plan for the queues failed"
assert_plan_creates_only "$TF_DIR/wizard-sqs.tfplan" "${SQS_TARGETS[@]}"
confirm "Apply these SQS resources (free tier, \$0/month)?" \
  || fail "aborted — the budget alarm stands, no queues were created"
tf apply wizard-sqs.tfplan || fail "terraform apply of the queues failed"
say "Queues created."
pause

# ── Stage 7: verify the footprint + capture the URLs ──────────────────────
stage "Verify footprint and capture queue URLs"
say "Re-planning the same targets — this should show no pending changes:"
plan_rc=0
tf plan -input=false -detailed-exitcode "${SQS_TARGET_FLAGS[@]}" "-target=$BUDGET_TARGET" >/dev/null 2>&1 || plan_rc=$?
case $plan_rc in
  0) say "Clean: no changes pending for this workflow's resources." ;;
  2) fail "targeted re-plan still shows pending changes — inspect with: terraform -chdir=terraform plan" ;;
  *) fail "targeted re-plan errored — run 'terraform -chdir=terraform plan' to see why" ;;
esac
ACTUAL_STATE=$(tf state list | sort)
EXPECTED_STATE=$(printf '%s\n' "$BUDGET_TARGET" "${SQS_TARGETS[@]}" | sort)
[[ "$ACTUAL_STATE" == "$EXPECTED_STATE" ]] \
  || fail "Terraform state holds resources beyond this wizard's footprint: $(printf '%s ' $ACTUAL_STATE)"
say "State holds exactly the 4 expected resources; everything else in"
say "terraform/ remains never-applied."
QUEUE_URL=$(aws sqs get-queue-url --queue-name "$QUEUE_NAME" --region "$REGION" --query QueueUrl --output text) \
  || fail "could not resolve the episode queue URL"
DLQ_URL=$(aws sqs get-queue-url --queue-name "${QUEUE_NAME}-dlq" --region "$REGION" --query QueueUrl --output text) \
  || fail "could not resolve the DLQ URL"
say ""
say "Paste this as the §9.1 configuration block of the real run"
say "(docs/SETUP_WINDOWS.md, on the Windows machine — PowerShell):"
say ""
printf '    $SQS_ENDPOINT = "https://sqs.%s.amazonaws.com"\n' "$REGION"
printf '    $QUEUE_URL = "%s"\n' "$QUEUE_URL"
printf '    $DLQ_URL = "%s"\n' "$DLQ_URL"
printf '    $RUN_ID = "sqs-live"\n'
printf '    $REPORT = "results/distributed/live_report.json"\n'
say ""
note "Re-print any time: re-run this wizard (it is idempotent), or"
note "aws sqs get-queue-url --queue-name $QUEUE_NAME --region $REGION"
pause

# ── Stage 8: cost statement + keep-or-destroy ─────────────────────────────
stage "Cost and the keep-or-destroy decision"
say "Monthly cost of what this wizard applied: \$0"
step "SQS: permanent free tier is 1M requests/month; the live run uses hundreds"
step "Budget alarm: notification-only budgets are free (only budget *actions* cost)"
say ""
say "Recommendation: KEEP the queues until the live distributed run (#26) is"
say "done — its runbook consumes the URLs printed above. Destroying and"
say "re-running this wizard later is also fine; it is idempotent."
if confirm "Destroy the two queues now instead of keeping them?"; then
  tf destroy "${SQS_TARGET_FLAGS[@]}" || fail "targeted destroy failed"
  say "Queues destroyed — the URLs printed in stage 7 are now invalid; re-run"
  say "this wizard to recreate the queues before the #26 sitting."
  say "The budget alarm stays as the account's safety net."
  note "(Remove it too, if ever wanted: terraform -chdir=terraform destroy -target=$BUDGET_TARGET)"
else
  say "Keeping the queues for #26. Record this on the issue."
fi

finish
